### ISSUE TITLE
Objects that share the same time

### ISSUE THREAD

**Issue by krillmcrawl** [dwilhelm89/LeafletSlider#31]
Hi! Great tool.

Is it possible to have all objects that share the same time to show at once? Lets say I have 5 objects, two of the have the same time, I want both of them to be visible at the same time. Also is there a function I could call to step forward or backward one timestep instead of using the slider?

Best Regards,

Kristian

**Comment by dwilhelm89** [comment]
Hi,

at the moment it is not possible to show several features at once based on the timestamp. It would only be possible to define the "step" variable to show multiple features on each step.

The Slider is based on the jQuery UI slider. Therefore you can use it's methods to change the slider:
E.g. ````$("#leaflet-slider").slider( "values", [1,15])````
The the API for more information: http://api.jqueryui.com/slider/
