### ISSUE TITLE
$(...).slider is not a function

### ISSUE THREAD

**Issue by odorsey** [dwilhelm89/LeafletSlider#33]
Hello! I'm using leaflet-slider for a project and ran into a bit of an issue. I was hoping that you could help me out.

I'm calling my markers from a MySQL database and encoding them into JSON so that they will dynamically update whenever my database is updated. All data relating to every marker is stored in one variable called "markers." I'm attempting to implement the leaflet-Slider with a layer group only consisting of my variable called "markers." 

So this is what my JavaScript looks like (after the necessary JS files have been called):
```
<script>
var json_data = <?php echo json_encode($data); ?>;

function init() {
  var sliderControl = null;

  var map = L.map('map', { zoomControl: false })
  .setView([41.146, -98.086], 4);
  new L.Control.Zoom({ position: 'topright' }).addTo(map);

  map.scrollWheelZoom.disable(); // disables the mouse wheel scroll...
    map.once('focus', function() { map.scrollWheelZoom.enable(); });// at least until you click once on the map
      mapLink = '<a href="http://openstreetmap.org">OpenStreetMap</a>';
      L.tileLayer(
        'http://a.tile.mapbox.com/v3/odorsey.jnj5k592/{z}/{x}/{y}.png', {
        maxZoom: 18
        }).addTo(map);
  map.attributionControl.setPrefix(''); // Don't show the 'Powered by Leaflet' text.

  for (var i = 0; i < json_data.length; i++) {
    var markers = L.marker([json_data[i].latitude, json_data[i].longitude], {customID: json_data[i].victimID})
    .bindPopup(json_data[i].firstName + ' ' + json_data[i].lastName + '<br>' + '<strong>Date:</strong>' + ' ' + json_data[i].dateOccurred)
    .addTo(map);
  }

  layerGroup = L.layerGroup([markers]);
  var sliderControl = L.control.sliderControl({layer:layerGroup, follow: true});
  map.addControl(sliderControl);
  sliderControl.startSlider();

  map.on('popupopen', function(centerMarker) {
    var cM = map.project(centerMarker.popup._latlng);
    cM.y -= centerMarker.popup._container.clientHeight/350
    map.setView(map.unproject(cM),13, {animate: true});
  })
} //end of function init()
```

However, when I try and implement all of this, I get an error in the console stating that 
```$(...).slider is not a function```... any idea on what I might be doing wrong? Thanks in advance!

**Comment by dwilhelm89** [comment]
Do you have the necessary libararies included?
- jQuery, jQueryUI?

And are they successfuly loaded before the script is executed?

If so, could you give a few more details where in the script the error occurs?

**Comment by odorsey** [comment]
Yes, the libraries should be loaded before the script is executed... hm. I've included the libraries before the previous code like this: 
```<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" type="text/css">
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script src="leafletSlider-master/SliderControl.js"></script>

<script>
var json_data = <?php echo json_encode($data); ?>;
```

The error message that appears is: 
![error](https://cloud.githubusercontent.com/assets/3502582/9071474/8aec3460-3ac3-11e5-965f-d8d952f37864.PNG)

If I go to that line, it's this one:
```
 $("#leaflet-slider").slider({
```

Do I need to maybe specify jquery-1.9.1.min.js instead of jquery-latest.min.js?

**Comment by odorsey** [comment]
It seems as though the slider has shown up now! I changed my jQuery and jQuery UI script links to the following: 
```
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
```

However, now I am working on the functionality, which doesn't seem to be working yet.

**Comment by odorsey** [comment]
This is a bit off-top, but how might one add the Leaflet-Slider without having it attach directly to the Leaflet map? If possible, I would like to place it in a div under my map.

**Comment by dwilhelm89** [comment]
Line 53 in the SliderControl.js where the Slider Div is appended. This could be adapted towards your needs.

````
$(sliderContainer).append('<div id="leaflet-slider" style="width:200px"><div class="ui-slider-handle"></div><div id="slider-timestamp" style="width:200px; margin-top:13px; background-color:#FFFFFF; text-align:center; border-radius:5px;"></div></div>');
````
