### ISSUE TITLE
Prevent markers from appearing

### ISSUE THREAD

**Issue by odorsey** [dwilhelm89/LeafletSlider#35]
If I wanted to briefly stop the process of markers being added to the map, what portion of the code would I need to alter? 

For instance, I understand that lines 131 through 165 of the code control markers from being cleared from the slider. I'm interested in the opposite...

**Comment by dwilhelm89** [comment]
As you already pointed out, removing markers is done for example on line 133 by ```map.removeLayer```.
A few lines later there are several statements for: ```map.addLayer```.
