### ISSUE TITLE
how to add clickable hyperlinks to geodata?

### ISSUE THREAD

**Issue by horstjens** [dwilhelm89/LeafletSlider#37]
i managed to run the demo from gh-pages branch locally but i wonder:

How could i add the functionality of clickable hyperlinks (url) to the datapoints in the points.json file so that the user can click on the markers and visit the url?

if i add an url property to the poinsts.json file:
```javascript
        {
            "type": "Feature",
            "properties": {
                "time": "2013-01-22 11:39:27+01",
                "url": "http://github.com"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    7.950666426,
                    52.169228982,
                    1
                ]
            }
        }
```
it is not clickable.

**Comment by dwilhelm89** [comment]
You could do this either within a popup (http://leafletjs.com/reference.html#popup) or via a marker click handler (http://leafletjs.com/reference.html#events).
But there is no automated way to do that. At least not with the LeafletSlider Plugin.
