### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by odelphia** [dwilhelm89/LeafletSlider#39]
Is there a way to autoplay the slider and repeat for continuous animation?

**Comment by dwilhelm89** [comment]
There is no built in way to do this. But it would easily be possible with a simple setInterval loop.

**Comment by dwilhelm89** [comment]
http://jsfiddle.net/q5R68/1/

**Comment by imlearningr** [comment]
Hi Dennis,
thank you so much for putting together the example in the above JSFiddle link. I have a question on JavaScript line 14. It seems to be an self-executing function. But all the reference I read uses this syntax:
`( function myFunction(){ .... function body .... } )();`

I don't understand why you put a $ at the beginning. I've searched high and low on google but haven't found an example quite like this. I know your code works, but I just couldn't figure out how and the syntax. Could you please help me understand it better?

thanks,
Yi

**Comment by dwilhelm89** [comment]
The $ is a sign that it uses jquery. 
See http://stackoverflow.com/a/3259561 for further information.

**Comment by imlearningr** [comment]
thank you very much Dennis. I am so glad that I understand it now :-)
