### ISSUE TITLE
Auto Timeslider

### ISSUE THREAD

**Issue by alexsays3** [dwilhelm89/LeafletSlider#40]
Hi, I really liked your time slider. It works perfectly with what I needed. However, I was just curious as to how I could add a feature where it could auto play, doesn't need to loop.

**Comment by dwilhelm89** [comment]
Programmatically setting the sliders value should be possible like this: http://jsfiddle.net/exXLV/8/ 
To automate the process you could simply use a setInterval function: http://www.w3schools.com/jsref/met_win_setinterval.asp.

**Comment by alexsays3** [comment]
Sorry but I am not very great at coding, I tried with what you gave me but I can't seem to get it to work. I believe the issue lies with the onclick function? Since the values are all static while I have variables that are based on user input. This is the code that I have right now:

            $("#leaflet-slider").slider({
                animate: "slow",
                range: _options.range,
                value: _options.value,
                values: _options.values,
                min: _options.minValue,
                max: _options.maxValue,
                step: 1,
                slide: function (e, ui) {
                    var map = _options.map;
                    var fg = L.featureGroup();
                    $("#slider-value").html(ui.value);
                    if(!!_options.markers[ui.value]) {
                        // If there is no time property, this line has to be removed (or exchanged with a different property)
                        if(_options.markers[ui.value].feature !== undefined) {
                            if(_options.markers[ui.value].feature.properties[_options.timeAttribute]){
                                if(_options.markers[ui.value]) $('#slider-timestamp').html(
                                    _extractTimestamp(_options.markers[ui.value].feature.properties[_options.timeAttribute], _options));
                            }else {
                                console.error("Time property "+ _options.timeAttribute +" not found in data");
                            }
                        }else {
                            // set by leaflet Vector Layers
                            if(_options.markers [ui.value].options[_options.timeAttribute]){
                                if(_options.markers[ui.value]) $('#slider-timestamp').html(
                                    _extractTimestamp(_options.markers[ui.value].options[_options.timeAttribute], _options));
                            }else {
                                console.error("Time property "+ _options.timeAttribute +" not found in data");
                            }
                        }

                        var i;
                        // clear markers
                        for (i = _options.minValue; i <= _options.maxValue; i++) {
                            if(_options.markers[i]) map.removeLayer(_options.markers[i]);
                        }
                        if(_options.range){
                            // jquery ui using range
                            for (i = ui.values[0]; i <= ui.values[1]; i++){
                               if(_options.markers[i]) {
                                   map.addLayer(_options.markers[i]);
                                   fg.addLayer(_options.markers[i]);
                               }
                            }
                        }else if(_options.follow){
                            for (i = ui.value - _options.follow + 1; i <= ui.value ; i++) {
                                if(_options.markers[i]) {
                                    map.addLayer(_options.markers[i]);
                                    fg.addLayer(_options.markers[i]);
                                }
                            }
                        }else{
                            for (i = _options.minValue; i <= ui.value ; i++) {
                                if(_options.markers[i]) {
                                    map.addLayer(_options.markers[i]);
                                    fg.addLayer(_options.markers[i]);
                                }
                            }
                        }
                    };
                    if(_options.rezoom) {
                        map.fitBounds(fg.getBounds(), {
                            maxZoom: _options.rezoom
                        });
                    }
                }

            });
            if (!_options.range && _options.alwaysShowDate) {
                $('#slider-timestamp').html(_extractTimeStamp(_options.markers[index_start].feature.properties[_options.timeAttribute], _options));
            }
            for (i = _options.minValue; i <= index_start; i++) {
                _options.map.addLayer(_options.markers[i]);
            }
        }
    });
    $("#slider-value").html(  $('#leaflet-slider').slider('value') );

    $("button").click( function(){
        $("#leaflet-slider").slider('value', _options.value);
    });
    L.control.sliderControl = function (options) {
        return new L.Control.SliderControl(options);
    };

    var sliderControl = null;

**Comment by dwilhelm89** [comment]
It's possible if you also expose the slide function:
```
L.Control.SliderControl = L.Control.extend({
    options: {
        position: 'topright',
        layers: null,
        maxValue: -1,
        minValue: 0,
        showAllOnStart: false,
        markers: null,
        range: false,
        follow: false,
        alwaysShowDate: false,
        rezoom: null
    },

    initialize: function(options) {
        L.Util.setOptions(this, options);
        this._layer = this.options.layer;

    },

    setPosition: function(position) {
        var map = this._map;

        if (map) {
            map.removeControl(this);
        }

        this.options.position = position;

        if (map) {
            map.addControl(this);
        }
        this.startSlider();
        return this;
    },

    onAdd: function(map) {
        this.options.map = map;

        // Create a control sliderContainer with a jquery ui slider
        var sliderContainer = L.DomUtil.create('div', 'slider', this._container);
        $(sliderContainer).append('<div id="leaflet-slider" style="width:200px"><div class="ui-slider-handle"></div><div id="slider-timestamp" style="width:200px; margin-top:13px; background-color:#FFFFFF; text-align:center; border-radius:5px;"></div></div>');
        //Prevent map panning/zooming while using the slider
        $(sliderContainer).mousedown(function() {
            map.dragging.disable();
        });
        $(document).mouseup(function() {
            map.dragging.enable();
            //Hide the slider timestamp if not range and option alwaysShowDate is set on false
            if (options.range || !options.alwaysShowDate) {
                $('#slider-timestamp').html('');
            }
        });

        var options = this.options;
        this.options.markers = [];

        //If a layer has been provided: calculate the min and max values for the slider
        if (this._layer) {
            var index_temp = 0;
            this._layer.eachLayer(function(layer) {
                options.markers[index_temp] = layer;
                ++index_temp;
            });
            options.maxValue = index_temp - 1;
            this.options = options;
        } else {
            console.log("Error: You have to specify a layer via new SliderControl({layer: your_layer});");
        }
        return sliderContainer;
    },

    onRemove: function(map) {
        //Delete all markers which where added via the slider and remove the slider div
        for (i = this.options.minValue; i < this.options.maxValue; i++) {
            map.removeLayer(this.options.markers[i]);
        }
        $('#leaflet-slider').remove();
    },

    slide: function(e, ui) {
        var map = _options.map;
        var fg = L.featureGroup();
        if (!!_options.markers[ui.value]) {
            // If there is no time property, this line has to be removed (or exchanged with a different property)
            if (_options.markers[ui.value].feature !== undefined) {
                if (_options.markers[ui.value].feature.properties.time) {
                    if (_options.markers[ui.value]) $('#slider-timestamp').html(_options.markers[ui.value].feature.properties.time.substr(0, 19));
                } else {
                    console.error("You have to have a time property");
                }
            } else {
                // set by leaflet Vector Layers
                if (_options.markers[ui.value].options.time) {
                    if (_options.markers[ui.value]) $('#slider-timestamp').html(_options.markers[ui.value].options.time.substr(0, 19));
                } else {
                    console.error("You have to have a time property");
                }
            }

            var i;
            // clear markers
            for (i = _options.minValue; i <= _options.maxValue; i++) {
                if (_options.markers[i]) map.removeLayer(_options.markers[i]);
            }
            if (_options.range) {
                // jquery ui using range
                for (i = ui.values[0]; i <= ui.values[1]; i++) {
                    if (_options.markers[i]) {
                        map.addLayer(_options.markers[i]);
                        fg.addLayer(_options.markers[i]);
                    }
                }
            } else if (_options.follow) {
                for (i = ui.value - _options.follow + 1; i <= ui.value; i++) {
                    if (_options.markers[i]) {
                        map.addLayer(_options.markers[i]);
                        fg.addLayer(_options.markers[i]);
                    }
                }
            } else {
                for (i = _options.minValue; i <= ui.value; i++) {
                    if (_options.markers[i]) {
                        map.addLayer(_options.markers[i]);
                        fg.addLayer(_options.markers[i]);
                    }
                }
            }
        };
        if (_options.rezoom) {
            map.fitBounds(fg.getBounds(), {
                maxZoom: _options.rezoom
            });
        }
    },

    startSlider: function() {
        _options = this.options;
        var index_start = _options.minValue;
        if (_options.showAllOnStart) {
            index_start = _options.maxValue;
            if (_options.range) _options.values = [_options.minValue, _options.maxValue];
            else _options.value = _options.maxValue;
        }
        $("#leaflet-slider").slider({
            range: _options.range,
            value: _options.value,
            values: _options.values,
            min: _options.minValue,
            max: _options.maxValue,
            step: 1,
            slide: this.slide
        });
        if (!_options.range && _options.alwaysShowDate) {
            $('#slider-timestamp').html(_options.markers[index_start].feature.properties.time.substr(0, 19));
        }
        for (i = _options.minValue; i <= index_start; i++) {
            _options.map.addLayer(_options.markers[i]);
        }
    }
});

L.control.sliderControl = function(options) {
    return new L.Control.SliderControl(options);
};
```

After that you can use the sliderControl object for the animation:
```
setInterval(function(){
            var current = $('#leaflet-slider').slider("value");
            var max = sliderControl.options.maxValue;
            var step = ++current % max;
            $('#leaflet-slider').slider("value", step);
            sliderControl.slide(null, {value: step});
        }, 1000);
```

**Comment by alexsays3** [comment]
ah thank you so much! To add a play button I would create the actual button on the html file and in the script I would change the setInterval to something like this?:

    setInterval($("button").click(function(){
                var current = $('#leaflet-slider').slider("value");
                var max = sliderControl.options.maxValue;
                var step = ++current % max;
                
                $('#leaflet-slider').slider("value", step)});
                sliderControl.slide(null, {value: step});
            )}, 1000);

**Comment by imlearningr** [comment]
Thank you so much Dennis! This works great for me. You are pretty awesome :+1:
