### ISSUE TITLE
Clustering Markers

### ISSUE THREAD

**Issue by atul1112** [dwilhelm89/LeafletSlider#42]
Hey,

Thanks for this great plugin.
I would really appreciate if you can help me in clustering the markers inside layerGroup.
I search over internet but nothing worked well.

so will be glad if you can help me out in this.

also is there any way that i can put a play button on map and on click event slider starts moving till the end.

Thanks,
Jay

**Comment by dwilhelm89** [comment]
Hi,
Regarding the clustering: Do you have any specific questions?

Play button: https://github.com/dwilhelm89/LeafletSlider/issues/40

Kind regards,
Dennis

**Comment by atul1112** [comment]
Thanks for your early response.

Yes, I want to show clustered markers based on slider.

As slider moves forward.. my markers increases so i want those in clustered format.

Regards,
Jay

**Comment by atul1112** [comment]
For Example:

http://ghybs.github.io/Leaflet.MarkerCluster.LayerSupport/examples/mcgLayerSupport-leafletslider.html

It is based on you slider, but I cant figure out how its done.

**Comment by dwilhelm89** [comment]
Did you check the Github instructions of their plugin: https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport

**Comment by atul1112** [comment]
yes i did.

But after doing it my slider wont show up.

**Comment by dwilhelm89** [comment]
You might be better off asking on their repository. I haven't used the MarkerCluster plugin.
