### ISSUE TITLE
Multiple layer with slider

### ISSUE THREAD

**Issue by atul1112** [dwilhelm89/LeafletSlider#43]
Hey,

I have one another issue.
Can i work with multiple layers in slidercontrol.

As right now i am not able to figure out any solution.

Thanks,
Jay

**Comment by dwilhelm89** [comment]
This currently not possible. You would have to somhow bring the features from the different layers into one array.
The initial setup is done in the "onAdd" method:

```
this.options.markers = [];

        //If a layer has been provided: calculate the min and max values for the slider
        if (this._layer) {
            var index_temp = 0;
            this._layer.eachLayer(function (layer) {
                options.markers[index_temp] = layer;
                ++index_temp;
            });
            options.maxValue = index_temp - 1;
            this.options = options;
        }
```
