### ISSUE TITLE
Missing code in html file

### ISSUE THREAD

**Issue by gloria-cho** [dwilhelm89/LeafletSlider#44]
Apparently you have to add these two stylesheets in index.html for the time-slider to show up (for my case):

<link type="text/css" rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
<link type="text/css" rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7/leaflet.css" />

**Comment by dwilhelm89** [comment]
Adding the necessary JS and CSS files is also mentioned in the README.
