### ISSUE TITLE
Slider not working with IE 11

### ISSUE THREAD

**Issue by johandanforth** [dwilhelm89/LeafletSlider#47]
Not sure if this Project is alive, but the slider is not working in IE 11 on Windows 10. When you click the slider, the whole map scrolls just as if the slider Control wasn't there. Works fine in chrome. I'll try to have a look at the issue myself.

**Comment by kubs3** [comment]
Hi, I have a same problem, do you fixed it ? Thanks

**Comment by johandanforth** [comment]
No I created my own control with a bootstrap slider instead.

Den 20 dec. 2016 3:52 em skrev kubs3 <notifications@github.com>:

Hi, I have a same problem, do you fixed it ? Thanks

**Comment by dwilhelm89** [comment]
Apparently this was a problem in Leaflet 0.7 which seems to be fixed in the newer versions.
https://github.com/Leaflet/Leaflet/issues/3666 
Upgrading to Leaflet 1.0 or higher could solve this issue
