### ISSUE TITLE
Items show not in time order, but in order in json

### ISSUE THREAD

**Issue by MtnBiker** [dwilhelm89/LeafletSlider#49]
If the data is not in time order, as the slider is moved appear in the order presented in the json. This may be hard to work around, but should be noted in the ReadMe.

This can be demonstrated by moving one of the Features from near the bottom to the top in the demo. It's easy to see because the sample is of something moving more or less in a line across the page.

This [Stackoverflow discussion ](http://stackoverflow.com/questions/35878087/timeslider-plugin-and-leaflet-markers-not-appearing-in-order/35881206#35881206) describes a fix. Maybe it could be used to add an option to sort.

If I could get it working for my own case maybe I could be more specific. But I'm lost in Leaflet and JS at the moment.

**Comment by dwilhelm89** [comment]
Feel free to submit a pull request if you managed to integrate the sort function properly in the code :-)
