### ISSUE TITLE
Feature Request:  Place slider off the map

### ISSUE THREAD

**Issue by sderrick** [dwilhelm89/LeafletSlider#52]
Any way I can place the slider off the map?

**Comment by dwilhelm89** [comment]
Hi, the slider is a simple JQuery slider which can be placed anywhere on a web page. You would have to change the code a little bit though.
The slider div is placed in the "onAdd" method:
```
$(sliderContainer).append('<div id="leaflet-slider" style="width:200px"><div class="ui-slider-handle"></div><div id="slider-timestamp" style="width:200px; margin-top:13px; background-color:#FFFFFF; text-align:center; border-radius:5px;"></div></div>');
```

This part could be appended to other HTML elements as well.
